# Generated by Django 5.1.1 on 2024-09-23 05:12

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='House-Number')),
                ('street_name', models.CharField(max_length=200, verbose_name='Street-Name')),
                ('city', models.CharField(max_length=200, verbose_name='City-Name')),
                ('state', models.CharField(max_length=200, verbose_name='State-Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('profile_image', models.ImageField(default='profile/default-profile.png', upload_to='profile/', verbose_name='Image')),
                ('speciality', models.CharField(max_length=200, verbose_name='Speciality')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Phone Number')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Year of Experience')),
                ('about', models.TextField(blank=True)),
                ('education', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='opd.address')),
            ],
        ),
    ]
