# Generated by Django 5.1.1 on 2024-09-22 20:07

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('profile_image', models.ImageField(default='profile/default-profile.png', upload_to='profile/', verbose_name='Image')),
                ('speciality', models.CharField(max_length=200, verbose_name='Speciality')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Year of Experience')),
                ('about', models.TextField(blank=True)),
                ('education', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
