# Generated by Django 5.1.1 on 2024-09-26 18:03

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(blank=True, max_length=60, null=True, verbose_name='House Number')),
                ('street_name', models.CharField(max_length=200, verbose_name='Street Name')),
                ('city', models.CharField(max_length=200, verbose_name='City Name')),
                ('state', models.CharField(max_length=200, verbose_name='State Name')),
                ('pincode', models.CharField(max_length=6, verbose_name='PinCode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=6, verbose_name='Blood Type')),
                ('height', models.CharField(max_length=10, verbose_name='Height')),
                ('weight', models.CharField(max_length=10, verbose_name='Weight')),
                ('medical_history', models.TextField(verbose_name='Medical History')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('profile_image', models.ImageField(default='profile/default-profile.png', upload_to='profile/', verbose_name='Image')),
                ('speciality', models.CharField(max_length=200, verbose_name='Speciality')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Phone Number')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Year of Experience')),
                ('about', models.TextField(blank=True)),
                ('education', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor', to='opd.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name of Patient')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date of appointment')),
                ('active', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='opd.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='opd.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Name of Item')),
                ('item_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity of Item')),
                ('item_price', models.FloatField(default=0, verbose_name='Price of Item')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_id', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='opd.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Opd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of OPD')),
                ('days_of_operation', models.CharField(max_length=100, verbose_name='Days of Operation')),
                ('max_patient_capacity', models.PositiveIntegerField(default=0, verbose_name='Maximum Patient Capacity')),
                ('active_patient', models.PositiveIntegerField(default=0, verbose_name='No. of Active_Patient')),
                ('no_of_appointment', models.PositiveIntegerField(default=0, verbose_name='No. of Appointment')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opd', to='opd.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=6, verbose_name='Gender')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', verbose_name='Contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='opd.address')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='opd.doctor')),
                ('medical_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='opd.medicaldata')),
            ],
        ),
    ]
