# Generated by Django 5.1.1 on 2024-09-22 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='House-Number')),
                ('street_name', models.CharField(max_length=200, verbose_name='Street-Name')),
                ('city', models.CharField(max_length=200, verbose_name='City-Name')),
                ('state', models.CharField(max_length=200, verbose_name='State-Name')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='opd.doctor')),
            ],
        ),
    ]
