# Generated by Django 5.1.1 on 2024-09-22 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_remove_doctor_address_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
