# Generated by Django 5.1.1 on 2024-09-24 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0002_doctor_user_alter_doctor_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.CharField(default=None, max_length=6, verbose_name='PinCode'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Inventory_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='Name-of-Item')),
                ('item_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity-of-Item')),
                ('item_price', models.FloatField(default=0, verbose_name='Price-of-Item')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_id', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='opd.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Opd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name-of-OPD')),
                ('days_of_operation', models.CharField(max_length=100, verbose_name='Days of Operation')),
                ('max_patient_capacity', models.PositiveIntegerField(default=0, verbose_name='Maximum-Patient-Capacity')),
                ('active_patient', models.PositiveIntegerField(default=0, verbose_name='No.-of-Active-Patient')),
                ('no_of_appointment', models.PositiveIntegerField(default=0, verbose_name='No.-of-Appointment')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='opd', to='opd.doctor')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='opd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='opd.opd'),
        ),
    ]
