# Generated by Django 5.1.1 on 2024-09-25 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0004_alter_address_city_alter_address_house_number_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inventory_Items',
            new_name='InventoryItems',
        ),
    ]
