# Generated by Django 5.1.1 on 2024-09-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0005_rename_inventory_items_inventoryitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryItems',
            new_name='InventoryItem',
        ),
    ]
