# Generated by Django 5.1.1 on 2024-09-25 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0006_rename_inventoryitems_inventoryitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='opd',
        ),
        migrations.AddField(
            model_name='inventory',
            name='doctor',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='opd.doctor'),
            preserve_default=False,
        ),
    ]
