# Generated by Django 5.1.1 on 2024-09-25 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opd', '0007_remove_inventory_opd_inventory_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name of Patient')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date of appointment')),
                ('active', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='opd.doctor')),
            ],
        ),
    ]
